Add bun support.
roblox-ts/create-roblox-ts pull request #15
Opened 2024-05-06 11:17 UTC by acopier

This PR Adds support for Bun, a blazingly fast JS runtime.

closes #13

2024-05-06 16:16 UTC, Dionysusnu commented
New iteration of roblox-ts/roblox-ts#2485

2024-05-06 16:26 UTC, Dionysusnu requested changes
> a blazingly fast JS runtime

Note that this won't allow you to use Bun's runtime itself, just the package manager. You'd need to change the compiler itself to support the runtime. We've tried in the past, and it turned out to be quite a lot of work.

2024-05-06 16:26 UTC, Dionysusnu commented on src/commands/init.ts
> +		init: "bun init -y && rm -rf index.ts .gitignore tsconfig.json README.md",
We don't need to delete `tsconfig.json`, the templates will overwrite it. The same goes for .gitignore, if git is being configured.

2024-05-06 16:26 UTC, Dionysusnu commented on src/commands/init.ts
> +		init: "bun init -y && rm -rf index.ts .gitignore tsconfig.json README.md",
I'm not a big fan of `rm -rf <>` in automated environments, they're bug-prone and very destructive if they go wrong.
Does bun have a way to init without these extra files?

2024-05-06 19:10 UTC, acopier commented on src/commands/init.ts
> +		init: "bun init -y && rm -rf index.ts .gitignore tsconfig.json README.md",
fixed

2024-05-06 19:11 UTC, acopier commented on src/commands/init.ts
> +		init: "bun init -y && rm -rf index.ts .gitignore tsconfig.json README.md",
fixed

2024-05-09 04:31 UTC, acopier commented
@Dionysusnu status?

2024-06-01 18:01 UTC, acopier commented
> @Dionysusnu status?

?

2024-06-01 18:05 UTC, Dionysusnu commented
I'm not the maintainer of roblox-ts, just a contributor.

2024-06-02 05:57 UTC, acopier commented
@osyrisrblx do you mind looking at this?

2024-06-02 18:03 UTC, Dionysusnu requested changes
I've looked into it some more, and I think it's a better option to stick with `npm init -y` for the init command. As explained in the earlier comment, bun can only work as a package manager for roblox-ts, the runtime isn't compatible. Therefore, I think it's better to init with `npm`, which just creates the `package.json`. The things `bun init` does on top of that are either incorrect for roblox-ts, or already covered by other parts of the init process.

I've left suggestions on how to add this in the code.

2024-06-02 18:03 UTC, Dionysusnu commented on src/commands/init.ts
> +		}
```suggestion
```

2024-06-02 18:03 UTC, Dionysusnu commented on src/commands/init.ts
> +		[PackageManager.Bun]: bunAvailable,
```suggestion
		[PackageManager.Bun]: npmAvailable && bunAvailable,
```

2024-06-02 18:03 UTC, Dionysusnu commented on src/commands/init.ts
> +		init: "bun init -y",
```suggestion
		init: "npm init -y",
```

2024-06-06 13:59 UTC, acopier commented on src/commands/init.ts
> +		init: "bun init -y",
We can't rely on user to have npm installed. NPM is actually optional.

2024-06-16 18:46 UTC, acopier commented on src/commands/init.ts
> +		init: "bun init -y",
The defaults don't matter if they are overwritten

2024-06-23 18:17 UTC, acopier commented
status?

2024-08-31 18:06 UTC, acopier commented
> I've looked into it some more, and I think it's a better option to stick with `npm init -y` for the init command. As explained in the earlier comment, bun can only work as a package manager for roblox-ts, the runtime isn't compatible. Therefore, I think it's better to init with `npm`, which just creates the `package.json`. The things `bun init` does on top of that are either incorrect for roblox-ts, or already covered by other parts of the init process.
> 
> I've left suggestions on how to add this in the code.

We cannot depend on NPM, some users don't even have NPM installed.

2024-08-31 18:10 UTC, Dionysusnu commented
My previous comment (in the suggestion thread) applies:
> If only bun is installed, I don't think we can reasonably provide the bun init option, because we wouldn't get the correct defaults for package.json.

2024-08-31 19:43 UTC, acopier commented
> My previous comment (in the suggestion thread) applies:
> 
> > If only bun is installed, I don't think we can reasonably provide the bun init option, because we wouldn't get the correct defaults for package.json.

I think the condition check is enough.

2024-09-02 02:57 UTC, Dionysusnu commented
What do you mean by condition check?

2025-09-27 20:28 UTC, closed without merging